#!/usr/bin/env bash
# ------------------------------------------------------------------
# Junjo
# A photo sorting tool. Drop your folder containing photos and videos,
# and it will organize them for you. Also works with Google Takeout.
#
# Usage:
#  junjo [OPTIONS] [FOLDER]
#
# Options:
#   -r[=0|1], --recursive[=0|1]     Recursively scan subdirectories (default: 1)
#   -v[=0|1], --verbose[=0|1]       Enable verbose output (default: 1)
#   -i[=0|1], --interactive[=0|1]   Enable interactive mode (default: 1)
#   --log-dir=PATH                  Directory to store log files (default: current directory)
#   --output-dir=PATH               Directory to store sorted files (default: ./output)
#
# Arguments:
#   FOLDER            Folder to scan (default: current directory)
#   FILE              File to analyze
#
# Usage Examples:
# To scan and organize a folder:
#   junjo -r -v /path/to/photos
#
# To run in interactive mode:
#   junjo -r -v -i /path/to/photos
#
# To specify a custom log directory:
#   junjo -r -v --log-dir="/var/log/junjo" /path/to/photos
#
# Author: Yoshi Nakamoto (@yoshimo2o) <yoshi@nkmt.to>
# License: MIT
# ------------------------------------------------------------------

# Init path variables
JUNJO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JUNJO_LIB_DIR="$JUNJO_DIR/lib"

# Init global variables & functions
source "$JUNJO_LIB_DIR/constants.sh"
source "$JUNJO_LIB_DIR/colors.sh"
source "$JUNJO_LIB_DIR/globals.sh"
source "$JUNJO_LIB_DIR/functions.sh"
source "$JUNJO_LIB_DIR/log.sh"
source "$JUNJO_LIB_DIR/debug.sh"
source "$JUNJO_LIB_DIR/controller.sh"
source "$JUNJO_LIB_DIR/media_scanner.sh"
source "$JUNJO_LIB_DIR/media_planner.sh"
source "$JUNJO_LIB_DIR/parser_file.sh"
source "$JUNJO_LIB_DIR/parser_takeout.sh"
source "$JUNJO_LIB_DIR/parser_exif.sh"
source "$JUNJO_LIB_DIR/parser_timestamp.sh"
source "$JUNJO_LIB_DIR/parser_device.sh"
source "$JUNJO_LIB_DIR/parser_software.sh"
source "$JUNJO_LIB_DIR/parser_live.sh"
source "$JUNJO_LIB_DIR/planner_destination.sh"
source "$JUNJO_LIB_DIR/planner_action.sh"
source "$JUNJO_DIR/config.defaults.ini"
source "$JUNJO_DIR/config.ini"

# Parse command line arguments
args=()
for arg in "$@"; do
  case $arg in
    -r|--recursive)
      JUNJO_SCAN_RECURSIVE=1
      ;;
    -r=*|--recursive=*)
      JUNJO_SCAN_RECURSIVE="${arg#*=}"
      ;;
    -v|--verbose)
      JUNJO_LOG_VERBOSE=1
      ;;
    -v=*|--verbose=*)
      JUNJO_LOG_VERBOSE="${arg#*=}"
      ;;
    -i|--interactive)
      JUNJO_INTERACTIVE=1
      ;;
    -i=*|--interactive=*)
      JUNJO_INTERACTIVE="${arg#*=}"
      ;;
    --debug)
      DEBUG=1
      ;;
    --log-dir=*)
      JUNJO_LOG_DIR="${arg#*=}"
      JUNJO_LOG_DIR="${JUNJO_LOG_DIR}"
      ;;
    --output-dir=*)
      JUNJO_OUTPUT_DIR="${arg#*=}"
      JUNJO_OUTPUT_DIR="${JUNJO_OUTPUT_DIR}"
      ;;
    *)
      args+=("$arg")
      ;;
  esac
done

# Use the last argument as scan_dir,
# else default to current directory.
if [[ ${#args[@]} -gt 0 ]]; then
  media_path="${args[-1]}"
fi

# If media_path is not a directory, print error and exit.
if [[ -d "$media_path" ]]; then
  JUNJO_SCAN_DIR="$media_path"
else
  echo "Error: Source folder '$media_path' does not exist." >&2
  exit 1
fi

# Check for required dependencies.
# If dependencies are missing, stop.
check_dependencies

# Init log.
# If unable to write logs, stop.
init_log || exit 1

# Start junjo
junjo_start