#!/usr/bin/env bash
# ------------------------------------------------------------------
# Junjo
# A photo sorting tool. Drop your folder containing photos and videos,
# and it will organize them for you. Also works with Google Takeout.
#
# Usage:
#  junjo [OPTIONS] [FOLDER|FILE]
#
# Options:
#   -r[=0|1], --recursive[=0|1]     Recursively scan subdirectories (default: 1)
#   -v[=0|1], --verbose[=0|1]       Enable verbose output (default: 1)
#   -i[=0|1], --interactive[=0|1]   Enable interactive mode (default: 1)
#
# Arguments:
#   FOLDER            Folder to scan (default: current directory)
#   FILE              File to analyze
#
# Usage Examples:
# To scan and organize a folder:
#   junjo -r -v /path/to/photos
#
# To run in interactive mode:
#   junjo -r -v -i /path/to/photos
#
# To specify a custom log directory:
#   junjo -r -v --log-dir="/var/log/junjo" /path/to/photos
#
# Author: Yoshi Nakamoto (@yoshimo2o) <yoshi@nkmt.to>
# License: MIT
# ------------------------------------------------------------------

# Init path variables
JUNJO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JUNJO_LIB_DIR="$JUNJO_DIR/lib"

# Init global variables & functions
source "$JUNJO_LIB_DIR/constants.sh"
source "$JUNJO_LIB_DIR/globals.sh"
source "$JUNJO_LIB_DIR/functions.sh"
source "$JUNJO_LIB_DIR/log.sh"
source "$JUNJO_LIB_DIR/debug.sh"
source "$JUNJO_LIB_DIR/controller.sh"
source "$JUNJO_LIB_DIR/media_scanner.sh"
source "$JUNJO_LIB_DIR/media_planner.sh"
source "$JUNJO_LIB_DIR/parser_file.sh"
source "$JUNJO_LIB_DIR/parser_takeout.sh"
source "$JUNJO_LIB_DIR/parser_exif.sh"
source "$JUNJO_LIB_DIR/parser_timestamp.sh"
source "$JUNJO_LIB_DIR/parser_device.sh"
source "$JUNJO_LIB_DIR/parser_software.sh"
source "$JUNJO_LIB_DIR/parser_live.sh"
source "$JUNJO_LIB_DIR/planner_destination.sh"
source "$JUNJO_LIB_DIR/planner_action.sh"
source "$JUNJO_DIR/config.defaults.ini"
source "$JUNJO_DIR/config.ini"

# Parse command line arguments
args=()
for arg in "$@"; do
  case $arg in
    -r|--recursive)
      JUNJO_SCAN_RECURSIVE=1
      ;;
    -v|--verbose)
      JUNJO_LOG_VERBOSE=1
      ;;
    -i|--interactive)
      JUNJO_INTERACTIVE=1
      ;;
    -i=*|--interactive=*)
      JUNJO_INTERACTIVE="${arg#*=}"
      ;;
    --debug)
      DEBUG=1
      ;;
    --log-dir=*)
      JUNJO_LOG_DIR="${arg#*=}"
      JUNJO_LOG_DIR="${JUNJO_LOG_DIR}"
      ;;
    --output-dir=*)
      JUNJO_OUTPUT_DIR="${arg#*=}"
      JUNJO_OUTPUT_DIR="${JUNJO_OUTPUT_DIR}"
      ;;
    *)
      args+=("$arg")
      ;;
  esac
done

# Use the last argument as scan_dir,
# else default to current directory.
if [[ ${#args[@]} -gt 0 ]]; then
  media_path="${args[-1]}"
fi

# If media_path is neither a file nor a directory, print error and exit.
if [[ ! -d "$media_path" && ! -f "$media_path" ]]; then
  echo "Error: '$media_path' is neither a valid directory nor a file." >&2
  exit 1
fi

# Check for required dependencies.
# If dependencies are missing, stop.
check_dependencies

# Init log.
# If unable to write logs, stop.
init_log || exit 1

# If media_path is a folder, scan it.
if [[ -d "$media_path" ]]; then

  JUNJO_SCAN_DIR="$media_path"

  # Print initial log message
  log_raw ""
  log_raw "$COLOR_LIGHT_ORANGE"
  log_raw "░░█ █░█ █▄░█ ░░█ █▀█ "
  log_raw "█▄█ █▄█ █░▀█ █▄█ █▄█ "
  log_raw "$COLOR_RESET"
  log_raw ""
  log_raw "Log directory: $JUNJO_LOG_DIR"
  log_raw "├── Main log: $JUNJO_LOG_FILE_NAME"
  log_raw "├── Scan log: $JUNJO_SCAN_LOG_FILE_NAME"
  log_raw "├── Plan log: $JUNJO_PLAN_LOG_FILE_NAME"
  log_raw "└── Sort log: $JUNJO_SORT_LOG_FILE_NAME"
  log_raw "Scan directory: $JUNJO_SCAN_DIR"
  log_raw "├── Full path: $(cd "$JUNJO_SCAN_DIR" && pwd)"
  log_raw "└── Recursive scan: $([[ $JUNJO_SCAN_RECURSIVE -eq 1 ]] && echo 'Yes' || echo 'No')"
  log_raw "Output directory: $JUNJO_OUTPUT_DIR"
  log_raw ""
  log_raw "If you are running without verbose (-v) flag,"
  log_raw "you can still monitor the logs in detail using:"
  log_raw "  Scan log: less -R +F $JUNJO_SCAN_LOG_FILE"
  log_raw "  Plan log: less -R +F $JUNJO_PLAN_LOG_FILE"
  log_raw "  Sort log: less -R +F $JUNJO_SORT_LOG_FILE"
  log_raw ""
  log_raw "When using \"less -R +F\", log starts streaming with colors:"
  log_raw "  Press CTRL-C: Pause streaming to scroll up/down, search, etc."
  log_raw "  Press SHIFT-F: Resume streaming."
  log_raw ""

  junjo_start
fi